name: MDAS

channels:
  - conda-forge
  - h2oai

dependencies:
  - python=3.6.5
  - pyjwt=1.7.1
  - redis-py=3.2.0
  - celery[redis]=4.1.1
  - psycopg2=2.7.5
  - h2oai_client=1.5.4
  - pip:
    - pymongo==3.7.2
    - bcrypt==3.1.4
    - coverage==4.5.1
    - sanic==19.03.1
    - sanic-cors==0.9.5
