- hosts: science

  tasks:

    - name: Ping Master
      ping:

    - name: Copy Private SSH Key
      copy:
        src: ../keys/mdas
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0400

    - name: Copy Public SSH Key
      copy:
        src: ../keys/mdas.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Install Python Pip
      apt:
        name: "python3-pip"
        state: latest
        update_cache: yes
      become: yes

    - name: Clone Kubespray
      git:
        repo: https://github.com/kubernetes-sigs/kubespray
        dest: /home/ubuntu/kubespray
        version: release-2.10

    - name: Install Kubespray Requirements
      pip:
        requirements: requirements.txt
      args:
        chdir: "/home/ubuntu/kubespray"
      become: yes

    - name: Copy Cluster Config File
      command: "cp -rfp inventory/sample inventory/mycluster"
      args:
        chdir: "/home/ubuntu/kubespray"

    - name: Update Kubespray Inventory
      shell: declare -a IPS=(10.0.0.10 10.0.1.10-10.0.1.12) && CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
      args:
        chdir: "/home/ubuntu/kubespray"
        executable: /bin/bash

    - name: Install Kubernetes
      shell: ansible-playbook -i inventory/mycluster/hosts.yml --become --become-user=root cluster.yml
      args:
        chdir: "/home/ubuntu/kubespray"
