- hosts: science

  tasks:

    - name: Ping Master
      ping:

    - name: Copy Private SSH Key
      copy:
        src: ../keys/mdas
        dest: /home/centos/.ssh/id_rsa
        owner: centos
        group: centos
        mode: 0400

    - name: Copy Public SSH Key
      copy:
        src: ../keys/mdas.pub
        dest: /home/centos/.ssh/id_rsa.pub
        owner: centos
        group: centos
        mode: 0644

    - name: Update Yum Packages (3-5 mins)
      yum:
        name: "*"
        state: latest
      become: yes

    - name: Install CentOS SCL
      yum:
        name: centos-release-scl
        state: latest
      become: yes

    - name: Install Python3
      yum:
        name: rh-python36
        state: latest
      become: yes

    - name: Create Python36 Profile Enabler
      copy:
        dest: "/etc/profile.d/enable_python36.sh"
        content: |
          #!/bin/bash
          source scl_source enable rh-python36
      become: yes

    - name: Install Git
      yum:
        name: git
        state: latest
      become: yes

    - name: Clone Kubespray
      git:
        repo: https://github.com/kubernetes-sigs/kubespray
        dest: /home/centos/kubespray

    - name: Get Python Version
      command: python --version
      register: python_version

    - name: Install Kubespray Requirements
      shell: /opt/rh/rh-python36/root/usr/bin/pip install -r requirements.txt
      args:
        chdir: "/home/centos/kubespray"
      become: yes
      when: python_version.stdout == "Python 3.6.3"

    - name: Copy Cluster Config File
      shell: cp -rfp inventory/sample inventory/mycluster
      args:
        chdir: "/home/centos/kubespray"

    - name: Update Ansible Inventory
      shell: declare -a IPS=(10.0.0.10 10.0.1.10-10.0.1.12) && CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
      args:
        chdir: "/home/centos/kubespray"

    - name: Install Kubernetes
      shell: ansible-playbook -i inventory/mycluster/hosts.yml --become --become-user=root cluster.yml
      args:
        chdir: "/home/centos/kubespray"
