- hosts: science

  tasks:

    - name: Ping Master
      ping:

    - name: Copy Private SSH Key
      copy:
        src: ../keys/mdas
        dest: /home/centos/.ssh/id_rsa
        owner: centos
        group: centos
        mode: 0400

    - name: Copy Public SSH Key
      copy:
        src: ../keys/mdas.pub
        dest: /home/centos/.ssh/id_rsa.pub
        owner: centos
        group: centos
        mode: 0644
